### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nl6720** [pierres/archiso-manager#9]
This project does not currently have a license. Please license it under one of the [free software licenses](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

CC other contributors: @dvzrv, @kpcyrd, @jelly.

**Comment by nl6720** [comment]
Personally I'd prefer `GPL-3.0-or-later` or `Apache-2.0`.

**Comment by kpcyrd** [comment]
I'm fine with `GPL-3.0-or-later` and most other licenses.

**Comment by nl6720** [comment]
CC @jelly too.

**Comment by jelly** [comment]
I'm fine with GPL-3.0-or-later and most other licenses.

**Comment by dvzrv** [comment]
I'm fine with `GPL-3.0-or-later` for my contributions
